# Generated by Django 2.2.4 on 2019-08-30 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsed_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=20)),
                ('text', models.CharField(max_length=300)),
                ('hashtag', models.CharField(max_length=200)),
                ('link', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='BlogData',
        ),
    ]
