# Generated by Django 2.2.4 on 2019-08-30 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsed_data', '0002_auto_20190830_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snsdata',
            name='author',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='snsdata',
            name='hashtag',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='snsdata',
            name='text',
            field=models.CharField(max_length=3000),
        ),
    ]
